server:
  port: 1111

eureka:
  client:
      serviceUrl:
          defaultZone: http://localhost:1112/eureka/
      healthcheck:
          enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.int}
    metadata-map:
          zone: shanghai

spring:
  application:
    name: server-peer1