spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.8.140:3306/sa_s_infopublish?useUnicode=true&characterEncoding=utf8&useSSL=false
        username: root
        password: handsmap123
server:
    port: 8099
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

mybatis:
    typeAliasesPackage: com.maomi.domain
    mapper-locations: classpath:mapper/*.xml
